### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by zsjhhh** [MingSun-Tse/Collaborative-Distillation#10]
Hi,
I got an error like this,

Traceback (most recent call last):
  File "main.py", line 73, in <module>
    net = TrainSE_With_WCTDecoder(args).cuda()
  File "/home/ubuntu/ZSJ/Collaborative-Distillation-master/model/model.py", line 8, in __init__
    self.BE = eval("model_original.Encoder%d" % args.stage)(args.BE, fixed=True)
  File "/home/ubuntu/ZSJ/Collaborative-Distillation-master/model/model_original.py", line 472, in __init__
    load_param(t7_model, 0,  self.conv0)
  File "/home/ubuntu/ZSJ/Collaborative-Distillation-master/utils.py", line 66, in load_param_from_t7
    model.get(in_layer_index).weight.float())
TypeError: 'NoneType' object is not callable

I have downloaded wct_models and BD models.
Is that because the pytorch version? I use pytorch-1.4.0. If so, will you release a pytorch>=1.0 version?
Thank you very much.

**Comment by nickyvdz-art** [comment]
not sure if this is specific to your problem; but it seems like its

pytorch==0.4.1

**Comment by zsjhhh** [comment]
When I used pytorch=1.14.0, I use torchfile.load instead of load_lua, and then the error appeared.
I created a new virtual environment and installed pytorch=0.4.1， then the problem gone.

**Comment by MingSun-Tse** [comment]
At this point, I don't have more practical suggestions about how to run our code on environments other than [that](https://github.com/MingSun-Tse/Collaborative-Distillation#environment) we suggested. So I am closing this issue. If anyone still has problem with it, please let me know.
