### ISSUE TITLE
Fedora 32 Workstation

### ISSUE THREAD

**Issue by nickyvdz-art** [MingSun-Tse/Collaborative-Distillation#12]
Hi again,

thank you for your help - the little bits and pieces helped me to understand conda / environment / etc.

awesome!

i can now confirm for you, works fine on latest Fedora 32 Workstation

once I've had my fun, I will attempt again in my Windows drive and let you know.

Kind regards and many thanks, it is unreal how fast this is.

**Comment by MingSun-Tse** [comment]
Very glad that our work can help you! Let me know if you have more questions.
