### ISSUE TITLE
No module named 'torch.utils.serialization

### ISSUE THREAD

**Issue by ioannist** [MingSun-Tse/Collaborative-Distillation#13]
UDA_VISIBLE_DEVICES=0 python WCT.py --debug --mode original
-->

```
Traceback (most recent call last):
  File "WCT.py", line 10, in <module>
    from util_wct import WCT
  File "/home/ioannis/Desktop/Collaborative-Distillation/PytorchWCT/util_wct.py", line 3, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'
```

**Comment by ioannist** [comment]
If I try to install the requirements...

```
  ERROR: Could not find a version that satisfies the requirement torch==0.4.1 (from -r requirements.txt (line 3)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==0.4.1 (from -r requirements.txt (line 3))
```

**Comment by ioannist** [comment]
Installed the dependencies form requirements file and it works. Had to downgrade python from 3.8 to 3.6.9 too in the conda env.

**Comment by inmchoi** [comment]
when pytorch updated 0.4 to 1.1, they got rid of all legacy stuff like serialization
so if you use 0.4 version, it will be solved

**Comment by MingSun-Tse** [comment]
At this point, I don't have more practical suggestions about how to run our code on environments other than [that](https://github.com/MingSun-Tse/Collaborative-Distillation#environment) we suggested.  So I am closing this issue. If anyone still has problem with it, please let me know.
