### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by ztt0821** [MingSun-Tse/Collaborative-Distillation#14]
Hi, when I want to test the code, I found the following problem.
Traceback (most recent call last):
  File "WCT.py", line 109, in <module>
    wct = WCT(args).cuda()
  File "/public/ttzhang9/Collaborative-Distillation-master/PytorchWCT/util_wct.py", line 59, in __init__
    self.e5 = SmallEncoder5_16x_aux(args.e5); self.d5 = SmallDecoder5_16x_aux(args.d5)
  File "/public/ttzhang9/Collaborative-Distillation-master/model/model_cd.py", line 713, in __init__
    weights = torch.load(model, map_location=lambda storage, location: storage)
  File "/home/grads/ttzhang9/anaconda3/envs/ttpytorch0.4/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/grads/ttzhang9/anaconda3/envs/ttpytorch0.4/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: unpickling stack underflow

I use  this "python WCT.py --debug --mode 16x " and keep the default setting in WCT.py
"
elif args.mode == "16x":
  args.e5 = '../trained_models/wct_se_16x_new/5SE.pth'
  args.e4 = '../trained_models/wct_se_16x_new/4SE.pth'
  args.e3 = '../trained_models/wct_se_16x_new/3SE.pth'
  args.e2 = '../trained_models/wct_se_16x_new/2SE.pth'
  args.e1 = '../trained_models/wct_se_16x_new/1SE.pth'
  args.d5 = '../trained_models/wct_se_16x_new_sd/5SD.pth'
  args.d4 = '../trained_models/wct_se_16x_new_sd/4SD.pth'
  args.d3 = '../trained_models/wct_se_16x_new_sd/3SD.pth'
  args.d2 = '../trained_models/wct_se_16x_new_sd/2SD.pth'
  args.d1 = '../trained_models/wct_se_16x_new_sd/1SD.pth'
".
I found the ".pth" file, for example "5SE.pth" file only has 1kb size. I think may be we need to use "20191109-211322_E20.pth". But I don't know which stage it belongs to.

**Comment by MingSun-Tse** [comment]
Hi @ztt0821 , thanks for your interest in our work. `5SE.pth` is a soft link. You can easily find its source by `ls -alh`, as follows.

```
lrwxrwxrwx  1 wanghuan wanghuan   23 Apr 21 11:03 1SE.pth -> 20191110-133713_E20.pth
-rw-rw-r--  1 wanghuan wanghuan 3.7M Apr 21 11:03 20191109-211322_E20.pth
-rw-rw-r--  1 wanghuan wanghuan 1.2M Apr 21 11:03 20191110-132643_E20.pth
-rw-rw-r--  1 wanghuan wanghuan 226K Apr 21 11:03 20191110-132705_E20.pth
-rw-rw-r--  1 wanghuan wanghuan  52K Apr 21 11:03 20191110-132713_E20.pth
-rw-rw-r--  1 wanghuan wanghuan  11K Apr 21 11:03 20191110-133713_E20.pth
lrwxrwxrwx  1 wanghuan wanghuan   23 Apr 21 11:03 2SE.pth -> 20191110-132713_E20.pth
lrwxrwxrwx  1 wanghuan wanghuan   23 Apr 21 11:03 3SE.pth -> 20191110-132705_E20.pth
lrwxrwxrwx  1 wanghuan wanghuan   23 Apr 21 11:03 4SE.pth -> 20191110-132643_E20.pth
lrwxrwxrwx  1 wanghuan wanghuan   23 Apr 21 11:03 5SE.pth -> 20191109-211322_E20.pth
```
