### ISSUE TITLE
Outputs are black pictures

### ISSUE THREAD

**Issue by moonmoonCL** [MingSun-Tse/Collaborative-Distillation#15]
Hi，

I replace EigenValueThre = 1e-100 with  EigenValueThre = 0  in util_wct.py,  but the outputs are black pictures.
something like this
![image](https://user-images.githubusercontent.com/55181046/100820341-f2e19a00-3488-11eb-82e4-eadb989cb48d.png)

why？
Thanks！

**Comment by MingSun-Tse** [comment]
Hi @moonmoonCL, when you use the original number EigenValueThre = 1e-100, does it work? Meanwhile, you may provide more details, like which snippet you use, so that I can reproduce your problem.

**Comment by moonmoonCL** [comment]
Thanks for your quick reply，
yes, when I use the original number EigenValueThre = 1e-100, it works very well.
I want to save all eigenvalues in diagonal matrix, so I replace EigenValueThre = 1e-100 with EigenValueThre = 0 in util_wct.py, and if I use the original number and comment out 
`        
        for i in range(cFSize[0]):
            if c_e[i] < EigenValueThre:
                k_c = i
                break
`
`
        for i in range(sFSize[0]):
            if s_e[i] < EigenValueThre:
                k_s = i
                break
`
the outputs are black pictures.

**Comment by MingSun-Tse** [comment]
Hi @moonmoonCL, I printed the eigenvalues ([c_e in the code](https://github.com/MingSun-Tse/Collaborative-Distillation/blob/0b5687a70bcea64f7b7e08b5177f63e21c0755d4/PytorchWCT/util_wct.py#L74)) when using the 16x models:

```
eigen values: [3.50370446e+02 2.06784668e+01 1.45766694e+01 1.12935617e+01
 9.74597606e+00 8.30892556e+00 7.12791294e+00 6.17595545e+00
 5.78257083e+00 5.65740988e+00 4.47304546e+00 3.72848304e+00
 3.63112827e+00 3.15717815e+00 3.04317053e+00 2.98929353e+00
 2.59324080e+00 2.43611878e+00 2.34234617e+00 2.12039079e+00
 2.03984017e+00 1.86273750e+00 1.82506672e+00 1.74881504e+00
 1.69784117e+00 1.57188066e+00 1.43888980e+00 1.34379726e+00
 1.25504146e+00 1.20965247e+00 1.15042239e+00 1.10289850e+00
 1.05864841e+00 1.01251026e+00 9.77901341e-01 9.32512119e-01
 8.74608250e-01 8.66071285e-01 8.28065644e-01 8.17862991e-01
 7.64982962e-01 7.42852053e-01 7.31578159e-01 6.98308006e-01
 6.73918731e-01 6.48104342e-01 6.25199221e-01 6.00435233e-01
 5.74073992e-01 5.59158200e-01 5.41596696e-01 5.22971539e-01
 4.87817760e-01 4.77491483e-01 4.54941685e-01 4.37346395e-01
 4.32836482e-01 4.19472925e-01 3.96502742e-01 3.81132225e-01
 3.77504758e-01 3.58108620e-01 3.48849825e-01 3.41317371e-01
 3.22567157e-01 3.11652514e-01 3.00562970e-01 2.90431132e-01
 2.77129484e-01 2.69194647e-01 2.51219882e-01 2.46456715e-01
 2.43149545e-01 2.32447736e-01 2.24081275e-01 2.12718443e-01
 2.06015827e-01 2.01894631e-01 1.88566519e-01 1.86171943e-01
 1.76821604e-01 1.68948695e-01 1.68337139e-01 1.56215011e-01
 1.49738657e-01 1.41227215e-01 1.37103991e-01 1.26578057e-01
 1.22217699e-01 1.15949615e-01 1.12051538e-01 1.10259488e-01
 9.94896936e-02 9.47217776e-02 8.58502819e-02 8.47781464e-02
 7.98813469e-02 6.24983970e-02 4.60831741e-02 1.18203533e-15
 8.43373557e-16 3.84291838e-16 3.11588544e-16 2.80409390e-16
 2.21741832e-16 1.90207668e-16 1.78007451e-16 1.61093163e-16
 1.43119980e-16 1.19172460e-16 1.09854444e-16 9.55024296e-17
 8.74718593e-17 7.41544967e-17 7.01764147e-17 5.94370155e-17
 5.53930253e-17 4.09118073e-17 3.64080660e-17 3.17268730e-17
 2.42518186e-17 1.72791750e-17 8.52884962e-18 3.89253112e-18
 1.82386112e-32 7.25518417e-49 0.00000000e+00 0.00000000e+00]
```
Note the last two eigenvalues are zero. In the subsequent code, there is a `c_d = (c_e[0:k_c]).pow(-0.5)`, so the zero will cause `inf` in `c_d` as I print below. This is the cause of black output.  
```
c_d:  tensor([5.3424e-02, 2.1991e-01, 2.6192e-01, 2.9757e-01, 3.2032e-01, 3.4692e-01,
        3.7456e-01, 4.0239e-01, 4.1585e-01, 4.2043e-01, 4.7282e-01, 5.1789e-01,
        5.2478e-01, 5.6280e-01, 5.7324e-01, 5.7838e-01, 6.2098e-01, 6.4069e-01,
        6.5339e-01, 6.8674e-01, 7.0017e-01, 7.3270e-01, 7.4022e-01, 7.5619e-01,
        7.6745e-01, 7.9761e-01, 8.3365e-01, 8.6265e-01, 8.9263e-01, 9.0922e-01,
        9.3233e-01, 9.5221e-01, 9.7191e-01, 9.9380e-01, 1.0112e+00, 1.0356e+00,
        1.0693e+00, 1.0745e+00, 1.0989e+00, 1.1058e+00, 1.1433e+00, 1.1602e+00,
        1.1691e+00, 1.1967e+00, 1.2181e+00, 1.2422e+00, 1.2647e+00, 1.2905e+00,
        1.3198e+00, 1.3373e+00, 1.3588e+00, 1.3828e+00, 1.4318e+00, 1.4472e+00,
        1.4826e+00, 1.5121e+00, 1.5200e+00, 1.5440e+00, 1.5881e+00, 1.6198e+00,
        1.6276e+00, 1.6711e+00, 1.6931e+00, 1.7117e+00, 1.7607e+00, 1.7913e+00,
        1.8240e+00, 1.8556e+00, 1.8996e+00, 1.9274e+00, 1.9951e+00, 2.0143e+00,
        2.0280e+00, 2.0741e+00, 2.1125e+00, 2.1682e+00, 2.2032e+00, 2.2256e+00,
        2.3029e+00, 2.3176e+00, 2.3781e+00, 2.4329e+00, 2.4373e+00, 2.5301e+00,
        2.5842e+00, 2.6610e+00, 2.7007e+00, 2.8107e+00, 2.8604e+00, 2.9367e+00,
        2.9874e+00, 3.0116e+00, 3.1704e+00, 3.2492e+00, 3.4129e+00, 3.4345e+00,
        3.5382e+00, 4.0001e+00, 4.6583e+00, 2.9086e+07, 3.4434e+07, 5.1012e+07,
        5.6651e+07, 5.9718e+07, 6.7155e+07, 7.2508e+07, 7.4952e+07, 7.8788e+07,
        8.3589e+07, 9.1603e+07, 9.5409e+07, 1.0233e+08, 1.0692e+08, 1.1613e+08,
        1.1937e+08, 1.2971e+08, 1.3436e+08, 1.5634e+08, 1.6573e+08, 1.7754e+08,
        2.0306e+08, 2.4057e+08, 3.4242e+08, 5.0686e+08, 7.4046e+15, 1.1740e+24,
               inf,        inf], dtype=torch.float64)
```

I checked the original VGG19 model, it does not have this problem, so probably the compression process makes the model compact, and some of the eigenvalues turn to exactly zero (I don't know why. Maybe we shall explore this in the future). Using the 1e-100 threshold simply to avoid these zeros (or, you can rewrite this line `c_d = (c_e[0:k_c]).pow(-0.5)` to get rid of the inf error). Generally, the last several eigenvalues are too small as you can see in the printed eigenvalues above. I checked with the original unpruned VGG19, using all the eigenvalues does not lead to perceptible stylization difference compared to the version that discards one or two eigenvalues.

If you have more questions, let me know.

**Comment by moonmoonCL** [comment]
Oh , I see.
Thank you so much!
