### ISSUE TITLE
Questions on Adain model file

### ISSUE THREAD

**Issue by penny4860** [MingSun-Tse/Collaborative-Distillation#17]
Thank you for revealing an interesting project!

 Will you release the distilled pretrained model file of adain style transfer?

**Comment by MingSun-Tse** [comment]
Hi @penny4860 , thanks for your interest in our work! We have the plan to release AdaIN code and models but probably cannot accomplish it in the short run. The implementation is not hard (we refer to this [pytorch AdaIN code](https://github.com/naoto0804/pytorch-AdaIN)). If you'd like to implement your own, let me know any time you have any questions.

**Comment by penny4860** [comment]
Thank you for your answer!
