### ISSUE TITLE
No module named 'torch.utils.serialization'

### ISSUE THREAD

**Issue by elkizana** [MingSun-Tse/Collaborative-Distillation#2]
I get this error when running the test script. 

`File "/root/Collaborative-Distillation/PytorchWCT/util_wct.py", line 3, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'`

**Comment by MingSun-Tse** [comment]
Please try to install Pytorch 0.4.1. 'torch.utils.serialization' is removed in pytorch1.x versions.

**Comment by elkizana** [comment]
Should I install it alongside 1.5 ?

**Comment by MingSun-Tse** [comment]
No. Just install pytorch==0.4.1 and torchvision==0.2.1
https://github.com/MingSun-Tse/Collaborative-Distillation#environment
