### ISSUE TITLE
RuntimeError: PyTorch was compiled without NumPy support

### ISSUE THREAD

**Issue by elkizana** [MingSun-Tse/Collaborative-Distillation#3]
I tried with NumPy 1.18 then downgraded to 1.15 with the same error message.

**Comment by MingSun-Tse** [comment]
I sense your problem may be that you didn't install the pytorch the right way. You may want to look at the standard installation guide and especially, use conda to manage the environment. https://pytorch.org/get-started/locally/

**Comment by elkizana** [comment]
When I comment line 128 in WCT.py no error is giving.
This is the full error output : 
`File "WCT.py", line 128, in <module>
    vutils.save_image(cImg.data.cpu(), out_path)
  File "/usr/local/lib/python3.7/site-packages/torchvision/utils.py", line 102, in save_image
    ndarr = grid.mul(255).clamp(0, 255).byte().permute(1, 2, 0).cpu().numpy()
RuntimeError: PyTorch was compiled without NumPy support
`

**Comment by MingSun-Tse** [comment]
Oh, that's interesting. But that functionality is still needed since you need to save stylized images. Could you please give your torchvision version?

**Comment by elkizana** [comment]
`torch                    0.4.1
torchvision              0.2.1`

Please after looking to this problem I would like to stylize my own picture, what's the correct command I should provide.
Thanks a lot for you efforts  MingSun-Tse !

**Comment by MingSun-Tse** [comment]
Hi, for now I don't know exactly what the problem is either. I can run on my computer normally based on what the README provides. To avoid potential environment issues, I just pushed the requirements.txt to the repo. I am sorry but you may need to rebuild your environment from scratch and try again. After that, if the problem remains, please let me know. Thanks!

**Comment by elkizana** [comment]
Strange. I uninstalled all the packages and reinstalled them from scratch from the requirements.txt file but didn't get rid of the error. This repo seems to be the only solution I found so far, so that I can achieve my purpose of transferring style to a large sized image  I have.

**Comment by elkizana** [comment]
MingSun-Tse How much gpu and ram resources are needed to treat a 10k pixel image ? Thanks.

**Comment by MingSun-Tse** [comment]
Hi Barbarosse -- I don't remember the exact numbers. I will run again and let you know after. Thanks. By the way, did you resolve the weird numpy problem?

**Comment by elkizana** [comment]
Hi, no not yet. But I managed to run it in Colab tough, but the results weren't satisfying for me, compared to other NST codes I used, the result was too off.

**Comment by MingSun-Tse** [comment]
Could you please report your environment (all used library versions) so that I can reproduce your error?

**Comment by elkizana** [comment]
OS : Ubuntu 20.04
Python : 3.7.6
All dependencies from your requirement.txt file.
Nvidia Driver : 440
Cuda : 10.1

**Comment by MingSun-Tse** [comment]
Please try python=3.6.9 https://github.com/MingSun-Tse/Collaborative-Distillation#environment
I don't know why, but it seems 3.7.6 does not work.

**Comment by elkizana** [comment]
OK
