### ISSUE TITLE
I got the error when installing torch 0.4.1

### ISSUE THREAD

**Issue by tuxxon** [MingSun-Tse/Collaborative-Distillation#5]
Hello.

I got the following error when installing `pip3 install -r requirements`.

```
ERROR: Could not find a version that satisfies the requirement torch==0.4.1 (from -r requirements.txt (line 3)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1)
ERROR: No matching distribution found for torch==0.4.1 (from -r requirements.txt (line 3))
```

My ubuntu version is ubuntu20.04 on wsl2.

Interestingly, when using `pip3 install torch`, v1.5.1 has been installed on ubuntu20.04 - wsl2.

Gordon Ahn.

**Comment by nickyvdz-art** [comment]
under conda i used:

conda install pytorch==0.4.1 -c pytorch

**Comment by MingSun-Tse** [comment]
I suggested using anaconda to install pytorch, which can save you a lot of time. I don't have more suggestions for now so I am closing this issue. Let me know if anyone still has questions.  Thanks!
