### ISSUE TITLE
CUDA + cuDNN 

### ISSUE THREAD

**Issue by nickyvdz-art** [MingSun-Tse/Collaborative-Distillation#7]
Hi,

Thank you so much for this! Not used it yet, looking forward to it. Unfortunately I am not a coder and quite clueless and new to all of this (python etc.), however I did get cysmith/neural-style-tf to work and can do about 1920px max.

So, apologies for any 'silly' questions - what versions of CUDA + cuDNN should be installed for this?

Many thanks again

**Comment by MingSun-Tse** [comment]
Hi,

On my desktop, it is CUDA10.2 without cuDNN (it's fine if you don't install it). CUDA mainly depends on the OS and driver version. So it is really case by case. A good try is to use anaconda to install the old-version pytorch (https://pytorch.org/get-started/previous-versions/). It will take care of the most version issues.

Best,

**Comment by nickyvdz-art** [comment]
Thank you sir for the quick reply; I will try to use it this evening; kind regards

**Comment by nickyvdz-art** [comment]
Thank you sir for the quick reply; I will try to use it this evening; kind regards
