### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ghost** [MingSun-Tse/Collaborative-Distillation#8]
Hi,

I get this syntax error when executing the code on Linux:

`Traceback (most recent call last):
  File "WCT.py", line 10, in <module>
    from util_wct import WCT
  File "/workspace/Collaborative/PytorchWCT/util_wct.py", line 13, in <module>
    from model.model_original import Encoder1, Encoder2, Encoder3, Encoder4, Encoder5
  File "/workspace/Collaborative/PytorchWCT/model.py", line 1
    ../model
    ^
SyntaxError: invalid syntax`

Is this a functionality which only works on other OSs?

**Comment by MingSun-Tse** [comment]
Hi,

The functionality should be fine on Linux. I tested it on Ubuntu1404 and 1604. In your log, it shows 'PytorchWCT/model.py', there is no such file in the `PytorchWCT` directory. You may want to check it out (it may occur because it is the out-of-time version, try to use the latest code)

I don't know the cause, but if you want to fix it, try:
1. in the `PytorchWCT` directory, `rm model`
2. `ln -s ../model .`

Let me know if the problem remains. Thanks.

Best,

**Comment by nickyvdz-art** [comment]
l also get this syntax error (no longer module error), after I did rm model and ln -s ../model

**Comment by ghost** [comment]
Hi,

Thanks for the reply. Yeah that fixed this problem, I had to do the same with the utils.py in PytorchWCT directory. But now I get the following error:

`[('UHD', True), ('UHD_contentPath', 'content/UHD_content'), ('UHD_stylePath', 'style/UHD_style'), ('alpha', 1), ('contentPath', 'content'), ('content_size', 0), ('d1', '../trained_models/wct_se_16x_new_sd/1SD.pth'), ('d2', '../trained_models/wct_se_16x_new_sd/2SD.pth'), ('d3', '../trained_models/wct_se_16x_new_sd/3SD.pth'), ('d4', '../trained_models/wct_se_16x_new_sd/4SD.pth'), ('d5', '../trained_models/wct_se_16x_new_sd/5SD.pth'), ('debug', True), ('e1', '../trained_models/wct_se_16x_new/1SE.pth'), ('e2', '../trained_models/wct_se_16x_new/2SE.pth'), ('e3', '../trained_models/wct_se_16x_new/3SE.pth'), ('e4', '../trained_models/wct_se_16x_new/4SE.pth'), ('e5', '../trained_models/wct_se_16x_new/5SE.pth'), ('log_mark', '20200723-0731'), ('mode', '16x'), ('num_run', 1), ('numpy', False), ('outf', 'stylized_results'), ('picked_content_mark', '.'), ('picked_style_mark', '.'), ('stylePath', 'style'), ('style_size', 0), ('synthesis', False), ('texturePath', 'style/texture')]                                       
                     Traceback (most recent call last):
  File "WCT.py", line 97, in <module>
    wct = WCT(args).cuda()
  File "/workspace/Collaborative/PytorchWCT/util_wct.py", line 44, in __init__
    self.e5 = SmallEncoder5_16x_aux(args.e5); self.d5 = SmallDecoder5_16x(args.d5)
  File "/workspace/Collaborative/PytorchWCT/model/model_cd.py", line 713, in __init__
    weights = torch.load(model, map_location=lambda storage, location: storage)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: unpickling stack underflow`

I used git pull and have torch 0.4.1 and torchvision 0.2.1 installed alongside python 3.6.9.

Greetings,

**Comment by nickyvdz-art** [comment]
"I had to do the same with the utils.py in PytorchWCT directory" - i had this problem also after following this fix for your model problem; 

"I don't know the cause, but if you want to fix it, try:

    in the PytorchWCT directory, rm model
    ln -s ../model ."

domingo - can you outline how you fixed the utils.py problem?

also, i am assuming you are on windows?

unfortunately I can not offer you help with your new problem

**Comment by ghost** [comment]
Hi, 

I currently am working on a linux docker container. There I just `rm utils.py` in the PytorchWCT directory and then created a symlink with `ln -s ../utils.py`. On Windows you can also create symlinks with `mklink /J` so in this example you would first delete the utils.py in PytorchWCT directory: `del utils.py` and then creakte a symlink to the utils.py in the above directory: `mklink /J utils.py ..\utils.py` (keep in mind you have to use backslashes in windows instead of normal slash for pathing)

Greetings

**Comment by nickyvdz-art** [comment]
Excellent sir, thank you so much I am way out of my depth with all of this, but I'll give it a go ;D
-------------------------------------------------------------------------------------------------------------------------------

I also end up at the same error as you describe above; 

[('UHD', True), ('UHD_contentPath', 'content/UHD_content'), ('UHD_stylePath', 'style/UHD_style'), ('alpha', 1), ('contentPath', 'content'), ('content_size', 0), ('d1', '../trained_models/wct_se_16x_new_sd/1SD.pth'), ('d2', '../trained_models/wct_se_16x_new_sd/2SD.pth'), ('d3', '../trained_models/wct_se_16x_new_sd/3SD.pth'), ('d4', '../trained_models/wct_se_16x_new_sd/4SD.pth'), ('d5', '../trained_models/wct_se_16x_new_sd/5SD.pth'), ('debug', True), ('e1', '../trained_models/wct_se_16x_new/1SE.pth'), ('e2', '../trained_models/wct_se_16x_new/2SE.pth'), ('e3', '../trained_models/wct_se_16x_new/3SE.pth'), ('e4', '../trained_models/wct_se_16x_new/4SE.pth'), ('e5', '../trained_models/wct_se_16x_new/5SE.pth'), ('log_mark', '20200723-0731'), ('mode', '16x'), ('num_run', 1), ('numpy', False), ('outf', 'stylized_results'), ('picked_content_mark', '.'), ('picked_style_mark', '.'), ('stylePath', 'style'), ('style_size', 0), ('synthesis', False), ('texturePath', 'style/texture')] Traceback (most recent call last): File "WCT.py", line 97, in <module> wct = WCT(args).cuda() File "/workspace/Collaborative/PytorchWCT/util_wct.py", line 44, in __init__ self.e5 = SmallEncoder5_16x_aux(args.e5); self.d5 = SmallDecoder5_16x(args.d5) File "/workspace/Collaborative/PytorchWCT/model/model_cd.py", line 713, in __init__ weights = torch.load(model, map_location=lambda storage, location: storage) File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 358, in load return _load(f, map_location, pickle_module) File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load magic_number = pickle_module.load(f) _pickle.UnpicklingError: unpickling stack underflow


damn gherkins...

**Comment by nickyvdz-art** [comment]
domingo - i beat my forehead to the keyboard some more, lol; whether i go for UHD or normal images, same unpickling error stack underflow trip; 

thanks for your help previously, its helped me understand rm / etc. i installed m2-base and am learning! HOORAY!
