### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by nickyvdz-art** [MingSun-Tse/Collaborative-Distillation#9]
again, apologies, I am truly out of my depth here...

managed to install everything ok; I think...

attempted to (while in anaconda prompt) run: python wct.py --debug --mode 16x --uhd

and the ModuleNotFoundError: No module named 'model'

**Comment by MingSun-Tse** [comment]
Hi, your problem may be because you download the code in .zip instead of using `git clone`.

To fix the problem, try:
1. in the PytorchWCT directory, `rm model`
2. `ln  -s  ../model  .`

Best,

**Comment by nickyvdz-art** [comment]
thank you again sir, that will indeed be the problem - i shall learn git clone. Sorry for the pain, wasn't aware of this zip issue, strange...

**Comment by nickyvdz-art** [comment]
thank you again sir, that will indeed be the problem - i shall learn git clone. Sorry for the pain, wasn't aware of this zip issue, strange...

**Comment by nickyvdz-art** [comment]
did git clone, 

"
    in the PytorchWCT directory, rm model
    ln -s ../model .
"

sorry, i am not following?
